### ISSUE TITLE
DeserializationError: Problem installing fixture

### ISSUE THREAD

**Issue by raymestalez** [metacademy/metacademy-application#56]
Migration fails when I'm trying to install metacademy-applicatoin:

    DeserializationError: Problem installing fixture '/home/ray/projects/metacademy/metacademy-application/server/apps/graph/fixtures/graph_fixture.json': Concept has no field named u'last_mod'
    /home/ray/projects/metacademy/meta_venv/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py:58: RuntimeWarning: SQLite received a naive datetime (2014-12-17 07:53:09.075002) while time zone support is active.
      RuntimeWarning)

    Makefile:24: recipe for target '/home/ray/projects/metacademy/local_dbs/django_db/django_db.sqlite' failed
    make: *** [/home/ray/projects/metacademy/local_dbs/django_db/django_db.sqlite] Error 1

**Comment by cjrd** [comment]
Yes, loading the static content has been problematic lately -- something about database migration and loading existing fixtures... If you checkout commit
4d940bdf8ae241b20b74512e9fc20f865e2c7881
load the db fixture
then checkout master
and do
`python app_server/manage.py migrate`
It should work

**Comment by sygi** [comment]
Could you elaborate on 'load the db fixture'?

**Comment by almereyda** [comment]
This is now completely broken for me.
I didn't collect all the errors of the ambiguity presented with here.
Just note that I tried to `rm -rf` everything, start from scratch and create a reproducible procedure. Impossible.

For now I will have to go back using the online instance, only. Though I'd love to seamlessly share graphs between my private offline instance and the public. Via *uploading* in the webinterface, of course. Now let's also start to think about versioning, once the above works again.

Leaving a note in the README that it currently doesn't build wouldn't hurt. Let's consider `master` broken for now.

A new integration scheme for code reviews through Pull Requests may help out here, too.

**Comment by cjrd** [comment]
@sygi I'm glad you figured out the migration. I'll try to fix this when I have time, though for now, I may just remove the serialized data so that the make procedure successfully completes, though the offline instance won't start with any content, then.

**Comment by cjrd** [comment]
Current build instructions should load the serialized data

**Comment by almereyda** [comment]
I am happy to read this and will try it out. Next stop: containerisation :rocket:
